### ISSUE TITLE
Why do we have 3 fleets?

### ISSUE THREAD

**Issue by colemonnahan** [ss3sim/ss3models#1]
Kot, can you remind me why we have a survey and CPUE? Wouldn't it be simpler to combine those into one?

**Comment by Kotkot** [comment]
the fleet 3 mirror fleet 1 (the fishery) and it is to calculate the fishery CPUE index.
It was decided at the beginning that we should do this way so that if we decide to change and have this fleet 3 doing different thing (e.g have an index of egg survey) we have the possibility. 
Felipe, I think it was you who were pushing for this. Did I summarize it well enough? Or did I miss something?

**Comment by fhurtado** [comment]
I actually cannot remember why was it that at the beginning we were saying that we could have 2 surveys instead of one. I agree with your explanation Kotaro, and if this does not affect anything between the EM and OM, nor does it imply making a workaround, I see no problem with leaving it as a placeholder. I think it had something to do with having different selectivities or something along the lines, but can't really recall. 

Sorry for the crappy answer.

**Comment by kellijohnson-NOAA** [comment]
Thanks @fhurtado for the description. I think this explanation is sufficient.
