### ISSUE TITLE
Model configuration to speed up runs

### ISSUE THREAD

**Issue by colemonnahan** [ss3sim/ss3models#14]
I'm starting this as a place to brainstorm ideas to minimize runtime by eliminating any unnecessary steps. I noticed that in at least some of the models we're doing this. Please add to the list and we can use this as a checklist in creating/checking new models.
1. Turn off ParmTrace in the starter file. Useful for debugging but should be set to 0 once the model is working.
2. Turn off bootstrapping in the starter file. We don't use bootstrapping and currently we write 1 iteration of it, which equates to generating an entire data file. This is particularly wasteful when calcomp data are used.
3. Detailed reporting: age-structured reports and cumreport? Do we need this in the starter file?

**Comment by iantaylor-NOAA** [comment]
I definitely agree with 1 and 2. 
On 3, some r4ss plots and diagnostics don't work without the detailed age-structured reporting and it's theoretically possible that some r4ss functions have bugs if that option is turned off because I haven't tested models with that setting in a while. But I think you could probably switch it off, see if you get any errors, and turn it back on (or fix the bugs) if you do get some.

**Comment by kellijohnson-NOAA** [comment]
What about # write to cumreport.sso (0=no,1=like&timeseries; 2=add 
survey fits), can that be turned to 0?

**Comment by iantaylor-NOAA** [comment]
Yes.
Only Rick Methot uses cumreport.sso as far as I know.
