### ISSUE TITLE
Starter files not consistent

### ISSUE THREAD

**Issue by colemonnahan** [ss3sim/ss3models#16]
@kellijohnson I'm working with this new package and the starter files are inconsistent still. The yellow and mackerel ones had bootstrapping turned off. The mackerel one is also capitalized. I thought these got standardized with that function? Does that need to be run again?

**Comment by kellijohnson-NOAA** [comment]
Git does not track the capitalization that closely, I think they were originally named with uppercase and even though they are lowercase on my machine it is not changing it.
I will do some more testing with all the models but I think I can turn bootstrapping back off for each species now that I fixed the extraction code. Just finished the tests and it seems like they all run. @colemonnahan can I turn the bootstrap back off so we are consistent?

**Comment by seananderson** [comment]
Regarding filename capitalization and Git: Git doesn't track filename capitalization changes on their own because I believe in some contexts (certain contexts on Windows?) operating systems are filename capitalization insensitive.

Anyways, `git mv` on its own won't work. You can either make one commit where you `git mv` to a temporary file and then `git mv` to the correct filename. Or you can do a `git mv --force` to do it in one commit. 

I just fixed the files in the mackerel folder.
