### ISSUE TITLE
An interactive table to check parameter values in ss3models

### ISSUE THREAD

**Issue by seananderson** [ss3sim/ss3models#19]
A bit of a tangent but I quickly put together an interactive table using Kelli's `get_parvalues` function. It lets you filter and sort all the parameter values in all the models:
https://dl.dropboxusercontent.com/u/254940/check-pars.html

If you want to recreate it (say with updated models), you can run `rmarkdown::render("extra/check-pars.Rmd")`.

Try filtering by parameter name or by model folder name in the search field. Or try sorting by different columns. Makes it easy to pick out where there are some inconsistencies.

**Comment by kellijohnson-NOAA** [comment]
This is amazing. Some of the parameters are not being picked yellow-age and I wonder why.

**Comment by iantaylor-NOAA** [comment]
This is indeed very useful. It would be great if this could be included in a set of table-making functions that could be applied to any SS model, not just within ss3sim.

The yellow-age em control file, https://github.com/ss3sim/ss3models/blob/master/inst/models/yellow-age/em/ss3.ctl, must have been created when the data file had the first fleet named "fishery1" rather than "fishery" as in the om control file. You could recreate the whole file or just find/replace "fishery1" with "fishery" to have em and om match in a remade table of parameter values.

**Comment by iantaylor-NOAA** [comment]
I'm assuming that the bounds haven't yet been standardized for these models because in both em and om, the yellow-age, agesel_1p_1\* parameters have a lower bound of age 40,0 and an initial value of 21.2.

However, the table also helped me notice the diversity of log(R0) parameters, from 5.6 for yellow to 18.7 for cod. I stand by the biological reasonableness of my prior suggestion of bounds that were 4 to 20, but it's possible that the different values of om log(R0) values will make a difference in performance if the models have much less far to wander in one direction than the other. 

Since fishing is represented by fishing effort rather than catch in all of your analyses, this parameter just sets an arbitrary scaling. You might consider changing the initial values to 10 or 12 for all models so that it is more central between the bounds. (You would want to confirm that this made no difference in results for a correctly specified model).

**Comment by cstawitz** [comment]
Yes, I have not standardized bounds for any of the age selectivity models
yet.

**Comment by seananderson** [comment]
I fixed up `fishery1`, `survey1`, and `survey2` in both yellowtail models and recreated the table: 
https://dl.dropboxusercontent.com/u/254940/check-pars.html

r4ss could use some interactive tables and graphs with an R Markdown Shiny app. Wouldn't be too hard to do.

**Comment by colemonnahan** [comment]
This is nice Sean thanks! We need to be careful about this since the OM does not use the ctl file for initial values, so the ones in this table could be wrong if the .par file doesn't match the .ctl file. @Kotkot can you confirm that the .ctl files were created from the .ss_new versions run from the OM .par files?

**Comment by kellijohnson-NOAA** [comment]
I added a column that checks the OM ctl versus par files (by reading in output from Report.sso), there were no errors between par and ctl in om but there were errors in M and steepness for hake-age and Survey Q for yellow-age. I fixed those and added the columns in the table with 3787faa4d1ccb0a300de0ce65a480bf858ebe787 along with some previous commits.

**Comment by Kotkot** [comment]
With Juan, we have created the .ctl files in the OM from control.ss_new,
for all models (as mentioned in the commit message).
However, we haven't changed the name of the fleet in the em .ctl files so
there could be mismatch.
Kot

**Comment by seananderson** [comment]
I updated the dynamic table with the new column Kelli added and any model tweaks and started the branch `gh-pages`. 

Any `.html` files in that folder will get rendered at `http://ss3sim.github.io/ss3models/`. For now, I copied the `extra/check-pars.html` file to `index.html` so it shows up as the homepage: http://ss3sim.github.io/ss3models  

This means anyone can update the table on the web by recreating the HTML file with `rmarkdown::render()`, merging `master` into `gh-pages` and copying the HTML file to `index.html`.

**Comment by kellijohnson-NOAA** [comment]
@seananderson would you mind updating the wiki page that I started this morning regarding this table and best practices on how to use it?
https://github.com/ss3sim/ss3models/wiki/Model-summary-table
Then I think we can close this as an issue.

**Comment by seananderson** [comment]
Thanks for starting that @kellijohnson . Sorry it took me a bit to get to this.

I just cleaned up the table and added instructions to [that wiki page](https://github.com/ss3sim/ss3models/wiki/Viewing-and-editing-the-model-setup-summary-table) you started.

The table itself is now found at http://htmlpreview.github.io/?https://github.com/ss3sim/ss3models/blob/master/extra/parameters.html

Note that the file is renamed, the table now shows all rows by default, and there's no funny branch stuff you have to do to update the table on the web. The magic sauce involves adding `http://htmlpreview.github.io/?` in front of the URL to get a rendered page.

So, anytime we make considerable changes to the model setup files, we should probably update that table. All it takes is running `rmarkdown::render("extra/parameters.Rmd")` and pushing the changes to GitHub.
