### ISSUE TITLE
Adding weight-at-age dummy data to the OMs

### ISSUE THREAD

**Issue by fhurtado** [ss3sim/ss3models#2]
For the empirical group we need the OMs to produce the weight-at-age data. This implies changing the .dat file by adding lines under "N_MeanSize-at-Age_obs" (i.e. below line 603 in the cod file as it stands right now). 

The question is then: would adding these lines to the operating model affect the other groups? Presumably it shouldn't make any difference at all if you're not using these data, but I want to make sure this is the case before making any change to the common OM files. If there is any issue, we will create a separate version of the OMs just for the group. Any thoughts on this?

**Comment by kellijohnson-NOAA** [comment]
You can use `sample_mlacomp` to add the data to the OM. Or I am  presuming you need mean weight-at-age which has yet to be implemented? Although the majority of the machinery is there and it is extremely similar to mean length-at-age. Would you ever want the amount of size at age data to change?

**Comment by fhurtado** [comment]
I am not sure I follow you. From what I understand, the `sample_mlacomp` function takes a .dat file and extracts the size-at-age info, and then samples it and stuff. I mean, line 48 says: 
`mlacomp <- datfile$MeanSize_at_Age_obs`
...so I assume that a .dat file with the expected values for size-at-age is needed in advance.

How would you use that function to add the data to the OM's dat file? Am I totally confused and asking stupid questions here?

**Comment by kellijohnson-NOAA** [comment]
Not a stupid question at all. This is a new development / attempt to 
make the models run faster and less need for user input.

We use an internal function called change_bin to add data to the OM 
based on what the sample_... functions need. We just haven't fully 
implemented it for all of the sample functions. I bet we could have the 
mean weight-at-age up and going in an hour though. Just because it is so 
similar to mean length-at-age.

**Comment by kellijohnson-NOAA** [comment]
would you want the same data in the mean size-at-age matrix as you want in the wtatage file? If so should we combine them? Or would you want to specify two separate case files? @colemonnahan -- what were you thinking would happen here?

**Comment by iantaylor-NOAA** [comment]
I assume you all have gotten this sorted out by now.
My understanding is that the OM would not need a wtatage input file but that file would be created using code written by Cole/Peter/Allan using values for mean length at age in the OM's data.ss_new for input to the EM. I don't know anything about adding the mean length at age data to the OM.

**Comment by allanhicks** [comment]
Hi all,

What we really need is the mean size-at-age, where lengths are the "size"
not "weight" (positive number for ageerror).  This way we sample from the
distribution of length-at-age, which has error, and convert to weight via
the length-weight relationship.

So, Felipe and I put in dummy data for mean size-at-age so that it returns
expected values of length-at-age in data.ss_new.  We read in these expected
values (using section=2 in the SS_readdat function) and sample from them
assuming this is the mean of the distribution of length-at-age.  So, Felipe
and I are under the impression that we set up the OM with all the
possibilities that we may need, and never change that (unless we have a
different assumption about a process). And then, use the SS3sim functions
to create estimation models and runs within a scenario.

Are we thinking about this correctly?

I have the function working and will upload it to ss3sim/Empirical/Rcode
shortly.  Also, I am going to upload the cod operating model and call it
cow (for cod wtatage), which means it has the mean size-at-age dummy
observations in it.

Thanks,
Allan

**Comment by iantaylor-NOAA** [comment]
I think that you are thinking about this correctly and uploading a "cow"
model will surely break nothing.

The complexity that Cole described on Monday (but maybe Allan and Felipe
weren't there) was that filling all the OMs with all possible combinations
of conditional age-at-length data would cause the the files to be huge so
some function that he was working on would create the minimal OM data for
necessary for the particular scenario being run. However, that is separate
from the the issue facing the Empirical group so waiting on that issue
shouldn't hinder progress toward getting Peter and the group some results.
-Ian

**Comment by allanhicks** [comment]
I just realized that the paradign in ss3sim is to have a single OM and
modify it with the ss3sim code (i.e., catches modified by chage_F
function).  I just uploaded a cod OM (called cowOM) in the Empirical
repository and put in index, length comps, age comps, and mean
length-at-age comp dummy data for all 100 years for the fishery and
survey.  The way that the sample_wtatage function works is to sample for
only the defined years, but if you define a year that does not have
expected values, then it will crash.

One thought is that it may be useful to sync or verify this with the age
comps to make sure that you do not have wtatage data for a year that has no
age comp (unless you really want that). I could see the case of no wtatage
data, but there are age comps.

Anyways, I'm slowly catching on. Thanks for your patience.
Allan

**Comment by kellijohnson-NOAA** [comment]
@peterkuriyama -- can you now use `ss3sim` and take a generic OM and have the package turn all the switches to create an empirical model? I am just curious if we can close this issue now?

**Comment by kellijohnson-NOAA** [comment]
@Kotkot It is my assumption that `ss3sim` is now fully functional with respect to running a simulation with empirical weight at age as long as the model is parameterized using age based selectivity. Is this assumption wrong?

**Comment by Kotkot** [comment]
We test tried with Peter a few cases and it worked great so far. 
However, I can't say definitely that it is fully functional for all possible models/cases... but in general, ss3sim is indeed functional for scenarios with empirical weight at age.
